apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-operator
  # Change to the name of the namespace where to install NATS Operator.
  # Alternatively, change to "nats-io" to perform a cluster-scoped deployment in supported versions.
  namespace: nats-pot

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-server
  namespace: nats-pot
