# permissions for end users to view dicomeventbridges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dicomeventbridge-viewer-role
rules:
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomeventbridges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomeventbridges/status
  verbs:
  - get
