# permissions for end users to view dicomeventdriveningestions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dicomeventdriveningestion-viewer-role
rules:
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomeventdriveningestions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomeventdriveningestions/status
  verbs:
  - get
