# permissions for end users to edit dicomstudybindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dicomstudybinding-editor-role
rules:
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomstudybindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomstudybindings/status
  verbs:
  - get
