# permissions for end users to edit dicomwebingestionservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dicomwebingestionservice-editor-role
rules:
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomwebingestionservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomwebingestionservices/status
  verbs:
  - get
