# permissions for end users to view dicomwebingestionservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dicomwebingestionservice-viewer-role
rules:
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomwebingestionservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomwebingestionservices/status
  verbs:
  - get
