# permissions for end users to edit dicomeventbridges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dicomeventbridge-editor-role
rules:
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomeventbridges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomeventbridges/status
  verbs:
  - get
