# permissions for end users to view dimseproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dimseproxy-viewer-role
rules:
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dimseproxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dimseproxies/status
  verbs:
  - get
