# permissions for end users to edit dimseingestionservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dimseingestionservice-editor-role
rules:
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dimseingestionservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dimseingestionservices/status
  verbs:
  - get
