# permissions for end users to view dimseingestionservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dimseingestionservice-viewer-role
rules:
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dimseingestionservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dimseingestionservices/status
  verbs:
  - get
