
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: system
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eventing.knative.dev
  resources:
  - brokers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eventing.knative.dev
  resources:
  - triggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomeventbridges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomeventbridges/finalizers
  verbs:
  - update
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomeventbridges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomeventdriveningestions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomeventdriveningestions/finalizers
  verbs:
  - update
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomeventdriveningestions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicominstancebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicominstancebindings/finalizers
  verbs:
  - update
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicominstancebindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomstudybindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomstudybindings/finalizers
  verbs:
  - update
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomstudybindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomwebingestionservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomwebingestionservices/finalizers
  verbs:
  - update
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dicomwebingestionservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dimseingestionservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dimseingestionservices/finalizers
  verbs:
  - update
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dimseingestionservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dimseproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dimseproxies/finalizers
  verbs:
  - update
- apiGroups:
  - imaging-ingestion.alvearie.org
  resources:
  - dimseproxies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sources.knative.dev
  resources:
  - sinkbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
