apiVersion: imaging-ingestion.alvearie.org/v1alpha1
kind: DimseIngestionService
metadata:
  name: ingestion
spec:
  bucketConfigName: imaging-ingestion
  bucketSecretName: imaging-ingestion
  applicationEntityTitle: DICOM-INGEST
  natsUrl: nats-secure.imaging-ingestion.svc.cluster.local:4222
  natsSecure: true
  natsSubjectRoot: DIMSE
  natsTokenSecret: ingestion-nats-secure-bound-token
  dicomEventDrivenIngestionName: core
  providerName: provider
  dimseService: {}
