apiVersion: imaging-ingestion.alvearie.org/v1alpha1
kind: DicomStudyBinding
metadata:
  name: fhir
spec:
  imagePullPolicy: Always
  bindingConfigName: study-binding-config
  bindingSecretName: study-binding-secret
  dicomEventDrivenIngestionName: core
  studyBinding:
    concurrency: 0
    maxReplicas: 3
    minReplicas: 0
