apiVersion: imaging-ingestion.alvearie.org/v1alpha1
kind: DicomwebIngestionService
metadata:
  name: ingestion
spec:
  imagePullPolicy: Always
  bucketConfigName: imaging-ingestion
  bucketSecretName: imaging-ingestion
  dicomEventDrivenIngestionName: core
  providerName: provider
  serviceConfigName: dicomweb-service-config
  stowService:
    concurrency: 0
    maxReplicas: 3
    minReplicas: 0
  wadoService:
    concurrency: 0
    maxReplicas: 3
    minReplicas: 0
