apiVersion: imaging-ingestion.alvearie.org/v1alpha1
kind: DicomInstanceBinding
metadata:
  name: stow
spec:
  bindingConfigName: instance-binding-config
  bindingSecretName: instance-binding-secret
  dicomEventDrivenIngestionName: core
  instanceBinding:
    concurrency: 0
    maxReplicas: 3
    minReplicas: 0
