//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
(C) Copyright IBM Corp. 2021

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonStatusSpec) DeepCopyInto(out *CommonStatusSpec) {
	*out = *in
	if in.SecondaryResources != nil {
		in, out := &in.SecondaryResources, &out.SecondaryResources
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonStatusSpec.
func (in *CommonStatusSpec) DeepCopy() *CommonStatusSpec {
	if in == nil {
		return nil
	}
	out := new(CommonStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentSpec) DeepCopyInto(out *DeploymentSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentSpec.
func (in *DeploymentSpec) DeepCopy() *DeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DicomEventBridge) DeepCopyInto(out *DicomEventBridge) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DicomEventBridge.
func (in *DicomEventBridge) DeepCopy() *DicomEventBridge {
	if in == nil {
		return nil
	}
	out := new(DicomEventBridge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DicomEventBridge) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DicomEventBridgeList) DeepCopyInto(out *DicomEventBridgeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DicomEventBridge, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DicomEventBridgeList.
func (in *DicomEventBridgeList) DeepCopy() *DicomEventBridgeList {
	if in == nil {
		return nil
	}
	out := new(DicomEventBridgeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DicomEventBridgeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DicomEventBridgeSpec) DeepCopyInto(out *DicomEventBridgeSpec) {
	*out = *in
	in.ImagePullSpec.DeepCopyInto(&out.ImagePullSpec)
	out.EventBridge = in.EventBridge
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DicomEventBridgeSpec.
func (in *DicomEventBridgeSpec) DeepCopy() *DicomEventBridgeSpec {
	if in == nil {
		return nil
	}
	out := new(DicomEventBridgeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DicomEventBridgeStatus) DeepCopyInto(out *DicomEventBridgeStatus) {
	*out = *in
	in.CommonStatusSpec.DeepCopyInto(&out.CommonStatusSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DicomEventBridgeStatus.
func (in *DicomEventBridgeStatus) DeepCopy() *DicomEventBridgeStatus {
	if in == nil {
		return nil
	}
	out := new(DicomEventBridgeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DicomEventDrivenIngestion) DeepCopyInto(out *DicomEventDrivenIngestion) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DicomEventDrivenIngestion.
func (in *DicomEventDrivenIngestion) DeepCopy() *DicomEventDrivenIngestion {
	if in == nil {
		return nil
	}
	out := new(DicomEventDrivenIngestion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DicomEventDrivenIngestion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DicomEventDrivenIngestionList) DeepCopyInto(out *DicomEventDrivenIngestionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DicomEventDrivenIngestion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DicomEventDrivenIngestionList.
func (in *DicomEventDrivenIngestionList) DeepCopy() *DicomEventDrivenIngestionList {
	if in == nil {
		return nil
	}
	out := new(DicomEventDrivenIngestionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DicomEventDrivenIngestionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DicomEventDrivenIngestionSpec) DeepCopyInto(out *DicomEventDrivenIngestionSpec) {
	*out = *in
	in.ImagePullSpec.DeepCopyInto(&out.ImagePullSpec)
	out.EventProcessor = in.EventProcessor
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DicomEventDrivenIngestionSpec.
func (in *DicomEventDrivenIngestionSpec) DeepCopy() *DicomEventDrivenIngestionSpec {
	if in == nil {
		return nil
	}
	out := new(DicomEventDrivenIngestionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DicomEventDrivenIngestionStatus) DeepCopyInto(out *DicomEventDrivenIngestionStatus) {
	*out = *in
	in.CommonStatusSpec.DeepCopyInto(&out.CommonStatusSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DicomEventDrivenIngestionStatus.
func (in *DicomEventDrivenIngestionStatus) DeepCopy() *DicomEventDrivenIngestionStatus {
	if in == nil {
		return nil
	}
	out := new(DicomEventDrivenIngestionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DicomInstanceBinding) DeepCopyInto(out *DicomInstanceBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DicomInstanceBinding.
func (in *DicomInstanceBinding) DeepCopy() *DicomInstanceBinding {
	if in == nil {
		return nil
	}
	out := new(DicomInstanceBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DicomInstanceBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DicomInstanceBindingList) DeepCopyInto(out *DicomInstanceBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DicomInstanceBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DicomInstanceBindingList.
func (in *DicomInstanceBindingList) DeepCopy() *DicomInstanceBindingList {
	if in == nil {
		return nil
	}
	out := new(DicomInstanceBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DicomInstanceBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DicomInstanceBindingSpec) DeepCopyInto(out *DicomInstanceBindingSpec) {
	*out = *in
	in.ImagePullSpec.DeepCopyInto(&out.ImagePullSpec)
	out.InstanceBinding = in.InstanceBinding
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DicomInstanceBindingSpec.
func (in *DicomInstanceBindingSpec) DeepCopy() *DicomInstanceBindingSpec {
	if in == nil {
		return nil
	}
	out := new(DicomInstanceBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DicomInstanceBindingStatus) DeepCopyInto(out *DicomInstanceBindingStatus) {
	*out = *in
	in.CommonStatusSpec.DeepCopyInto(&out.CommonStatusSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DicomInstanceBindingStatus.
func (in *DicomInstanceBindingStatus) DeepCopy() *DicomInstanceBindingStatus {
	if in == nil {
		return nil
	}
	out := new(DicomInstanceBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DicomStudyBinding) DeepCopyInto(out *DicomStudyBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DicomStudyBinding.
func (in *DicomStudyBinding) DeepCopy() *DicomStudyBinding {
	if in == nil {
		return nil
	}
	out := new(DicomStudyBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DicomStudyBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DicomStudyBindingList) DeepCopyInto(out *DicomStudyBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DicomStudyBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DicomStudyBindingList.
func (in *DicomStudyBindingList) DeepCopy() *DicomStudyBindingList {
	if in == nil {
		return nil
	}
	out := new(DicomStudyBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DicomStudyBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DicomStudyBindingSpec) DeepCopyInto(out *DicomStudyBindingSpec) {
	*out = *in
	in.ImagePullSpec.DeepCopyInto(&out.ImagePullSpec)
	out.StudyBinding = in.StudyBinding
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DicomStudyBindingSpec.
func (in *DicomStudyBindingSpec) DeepCopy() *DicomStudyBindingSpec {
	if in == nil {
		return nil
	}
	out := new(DicomStudyBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DicomStudyBindingStatus) DeepCopyInto(out *DicomStudyBindingStatus) {
	*out = *in
	in.CommonStatusSpec.DeepCopyInto(&out.CommonStatusSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DicomStudyBindingStatus.
func (in *DicomStudyBindingStatus) DeepCopy() *DicomStudyBindingStatus {
	if in == nil {
		return nil
	}
	out := new(DicomStudyBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DicomwebIngestionService) DeepCopyInto(out *DicomwebIngestionService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DicomwebIngestionService.
func (in *DicomwebIngestionService) DeepCopy() *DicomwebIngestionService {
	if in == nil {
		return nil
	}
	out := new(DicomwebIngestionService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DicomwebIngestionService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DicomwebIngestionServiceList) DeepCopyInto(out *DicomwebIngestionServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DicomwebIngestionService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DicomwebIngestionServiceList.
func (in *DicomwebIngestionServiceList) DeepCopy() *DicomwebIngestionServiceList {
	if in == nil {
		return nil
	}
	out := new(DicomwebIngestionServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DicomwebIngestionServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DicomwebIngestionServiceSpec) DeepCopyInto(out *DicomwebIngestionServiceSpec) {
	*out = *in
	in.ImagePullSpec.DeepCopyInto(&out.ImagePullSpec)
	out.StowService = in.StowService
	out.WadoService = in.WadoService
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DicomwebIngestionServiceSpec.
func (in *DicomwebIngestionServiceSpec) DeepCopy() *DicomwebIngestionServiceSpec {
	if in == nil {
		return nil
	}
	out := new(DicomwebIngestionServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DicomwebIngestionServiceStatus) DeepCopyInto(out *DicomwebIngestionServiceStatus) {
	*out = *in
	in.CommonStatusSpec.DeepCopyInto(&out.CommonStatusSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DicomwebIngestionServiceStatus.
func (in *DicomwebIngestionServiceStatus) DeepCopy() *DicomwebIngestionServiceStatus {
	if in == nil {
		return nil
	}
	out := new(DicomwebIngestionServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DimseIngestionService) DeepCopyInto(out *DimseIngestionService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DimseIngestionService.
func (in *DimseIngestionService) DeepCopy() *DimseIngestionService {
	if in == nil {
		return nil
	}
	out := new(DimseIngestionService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DimseIngestionService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DimseIngestionServiceList) DeepCopyInto(out *DimseIngestionServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DimseIngestionService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DimseIngestionServiceList.
func (in *DimseIngestionServiceList) DeepCopy() *DimseIngestionServiceList {
	if in == nil {
		return nil
	}
	out := new(DimseIngestionServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DimseIngestionServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DimseIngestionServiceSpec) DeepCopyInto(out *DimseIngestionServiceSpec) {
	*out = *in
	in.ImagePullSpec.DeepCopyInto(&out.ImagePullSpec)
	out.DimseService = in.DimseService
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DimseIngestionServiceSpec.
func (in *DimseIngestionServiceSpec) DeepCopy() *DimseIngestionServiceSpec {
	if in == nil {
		return nil
	}
	out := new(DimseIngestionServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DimseIngestionServiceStatus) DeepCopyInto(out *DimseIngestionServiceStatus) {
	*out = *in
	in.CommonStatusSpec.DeepCopyInto(&out.CommonStatusSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DimseIngestionServiceStatus.
func (in *DimseIngestionServiceStatus) DeepCopy() *DimseIngestionServiceStatus {
	if in == nil {
		return nil
	}
	out := new(DimseIngestionServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DimseProxy) DeepCopyInto(out *DimseProxy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DimseProxy.
func (in *DimseProxy) DeepCopy() *DimseProxy {
	if in == nil {
		return nil
	}
	out := new(DimseProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DimseProxy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DimseProxyList) DeepCopyInto(out *DimseProxyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DimseProxy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DimseProxyList.
func (in *DimseProxyList) DeepCopy() *DimseProxyList {
	if in == nil {
		return nil
	}
	out := new(DimseProxyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DimseProxyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DimseProxySpec) DeepCopyInto(out *DimseProxySpec) {
	*out = *in
	in.ImagePullSpec.DeepCopyInto(&out.ImagePullSpec)
	out.Proxy = in.Proxy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DimseProxySpec.
func (in *DimseProxySpec) DeepCopy() *DimseProxySpec {
	if in == nil {
		return nil
	}
	out := new(DimseProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DimseProxyStatus) DeepCopyInto(out *DimseProxyStatus) {
	*out = *in
	in.CommonStatusSpec.DeepCopyInto(&out.CommonStatusSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DimseProxyStatus.
func (in *DimseProxyStatus) DeepCopy() *DimseProxyStatus {
	if in == nil {
		return nil
	}
	out := new(DimseProxyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DimseServiceSpec) DeepCopyInto(out *DimseServiceSpec) {
	*out = *in
	out.DeploymentSpec = in.DeploymentSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DimseServiceSpec.
func (in *DimseServiceSpec) DeepCopy() *DimseServiceSpec {
	if in == nil {
		return nil
	}
	out := new(DimseServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventBridgeSpec) DeepCopyInto(out *EventBridgeSpec) {
	*out = *in
	out.DeploymentSpec = in.DeploymentSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventBridgeSpec.
func (in *EventBridgeSpec) DeepCopy() *EventBridgeSpec {
	if in == nil {
		return nil
	}
	out := new(EventBridgeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventProcessorSpec) DeepCopyInto(out *EventProcessorSpec) {
	*out = *in
	out.ServiceSpec = in.ServiceSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventProcessorSpec.
func (in *EventProcessorSpec) DeepCopy() *EventProcessorSpec {
	if in == nil {
		return nil
	}
	out := new(EventProcessorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePullSpec) DeepCopyInto(out *ImagePullSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePullSpec.
func (in *ImagePullSpec) DeepCopy() *ImagePullSpec {
	if in == nil {
		return nil
	}
	out := new(ImagePullSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceBindingSpec) DeepCopyInto(out *InstanceBindingSpec) {
	*out = *in
	out.ServiceSpec = in.ServiceSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceBindingSpec.
func (in *InstanceBindingSpec) DeepCopy() *InstanceBindingSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxySpec) DeepCopyInto(out *ProxySpec) {
	*out = *in
	out.DeploymentSpec = in.DeploymentSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxySpec.
func (in *ProxySpec) DeepCopy() *ProxySpec {
	if in == nil {
		return nil
	}
	out := new(ProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StowServiceSpec) DeepCopyInto(out *StowServiceSpec) {
	*out = *in
	out.ServiceSpec = in.ServiceSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StowServiceSpec.
func (in *StowServiceSpec) DeepCopy() *StowServiceSpec {
	if in == nil {
		return nil
	}
	out := new(StowServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StudyBindingSpec) DeepCopyInto(out *StudyBindingSpec) {
	*out = *in
	out.ServiceSpec = in.ServiceSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StudyBindingSpec.
func (in *StudyBindingSpec) DeepCopy() *StudyBindingSpec {
	if in == nil {
		return nil
	}
	out := new(StudyBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WadoServiceSpec) DeepCopyInto(out *WadoServiceSpec) {
	*out = *in
	out.ServiceSpec = in.ServiceSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WadoServiceSpec.
func (in *WadoServiceSpec) DeepCopy() *WadoServiceSpec {
	if in == nil {
		return nil
	}
	out := new(WadoServiceSpec)
	in.DeepCopyInto(out)
	return out
}
